apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: c01p006
spec:
    clusterNetwork:
        services:
            cidrBlocks: ["10.254.0.0/16"]
        pods:
            cidrBlocks: ["10.6.0.0/16"]
        serviceDomain: "cluster.local"
    providerConfig:
      value:
        apiVersion: "openstackproviderconfig/v1alpha1"
        kind: "OpenstackProviderConfig"

